pipeline {
    agent any

    tools {
        maven 'maven'
        java 'java'
    }

    stages {
        stage('Build') {
            steps {
                echo 'Building...'
                // Run Maven on a Unix agent.
                sh "mvn -f Calculadora/backend/pom.xml -Dmaven.test.failure.ignore=true clean package"
            }
        }
        stage('Test') {
            steps {
                echo 'Testing...'
            }
        }
    }
}